-- local chatgpt_setup, chatgpt = pcall(require, "spectre")
-- if not chatgpt_setup then
--     return
-- end

-- chatgpt.setup({
--     keymaps = {
--         close = { "<C-c>", "<Esc>" },
--         yank_last = "<C-y>",
--         scroll_up = "<C-u>",
--         scroll_down = "<C-d>",
--         toggle_settings = "<C-o>",
--         new_session = "<C-n>",
--         cycle_windows = "<Tab>",
--     },
-- })
